agent_options:
  path: ./lib/all/agent-options/agent-options.yml
labels:
org_settings:
  features:
    enable_host_users: true
    enable_software_inventory: true
  fleet_desktop:
    transparency_url: https://fleetdm.com/transparency
  host_expiry_settings:
    host_expiry_enabled: false
    host_expiry_window: 0
  integrations:
    conditional_access_enabled:
    custom_scep_proxy:
    digicert:
    google_calendar:
    jira:
    ndes_scep_proxy:
    zendesk:
  mdm:
    apple_business_manager:
    apple_server_url:
    end_user_authentication:
      entity_id:
      idp_name:
      issuer_uri:
      metadata:
      metadata_url:
    volume_purchasing_program:
  org_info:
    contact_url: https://fleetdm.com/company/contact
    org_logo_url: https://static.wikia.nocookie.net/eberron/images/b/bf/Dragonmarked_House_COA_Cannith.jpg
    org_logo_url_light_background:
    org_name: House Cannith
  secrets:
  - secret: $FLEET_GLOBAL_ENROLL_SECRET
  server_settings:
    ai_features_disabled: false
    deferred_save_host: false
    enable_analytics: true
    live_query_disabled: false
    query_report_cap: 0
    query_reports_disabled: false
    scripts_disabled: false
    server_url: https://fleet.skyreach.dev
  sso_settings:
    enable_jit_provisioning: false
    enable_sso: false
    enable_sso_idp_login: false
    entity_id:
    idp_image_url:
    idp_name:
    metadata:
    metadata_url:
  webhook_settings:
    activities_webhook:
      destination_url:
      enable_activities_webhook: false
    failing_policies_webhook:
      destination_url:
      enable_failing_policies_webhook: false
      host_batch_size: 0
      policy_ids:
    host_status_webhook:
      days_count: 0
      destination_url:
      enable_host_status_webhook: false
      host_percentage: 0
    interval: 24h0m0s
    vulnerabilities_webhook:
      destination_url:
      enable_vulnerabilities_webhook: false
      host_batch_size: 0
  yara_rules:
policies:
queries:
 - automations_enabled: false
   description: Collects operating system information from all devices enrolled in
    Fleet
   discard_data: false
   interval: 300
   logging: snapshot
   min_osquery_version:
   name: Collect operating system information
   observer_can_run: true
   platform: darwin,linux,windows
   query: SELECT * FROM os_version;
 - path: ./lib/all/queries/network_monitoring.yml
 - path: ./lib/all/queries/browser_extensions.yml
 - path: ./lib/linux/queries/linux_kernel_modules_and_extensions.yml
 - path: ./lib/linux/queries/linux_running_processes.yml
 - path: ./lib/linux/queries/linux_local_job_scheduling.yml
 - path: ./lib/linux/queries/linux_home_root_hidden_file_directory.yml
 - path: ./lib/linux/queries/linux_users_check.yml
 - path: ./lib/linux/queries/linux_network_connections.yml
 - path: ./lib/linux/queries/linux_browser_extensions.yml
 - path: ./lib/linux/queries/generic_linux.yml
 - path: ./lib/linux/queries/linux_command_execution.yml
 - path: ./lib/linux/queries/linux_relevant_folder_check.yml
 - path: ./lib/windows/queries/windows-incorrect_path_process.yml
 - path: ./lib/windows/queries/windows_service-persistence.yml
 - path: ./lib/windows/queries/windows_critical_service_status.yml
 - path: ./lib/windows/queries/windows_scheduled_tasks.yml
 - path: ./lib/windows/queries/windows-incorrect_parent_process.yml
 - path: ./lib/windows/queries/windows_generic_detection.yml
 - path: ./lib/windows/queries/windows_powershell_events.yml
 - path: ./lib/windows/queries/windows-registry-monitoring.yml
 - path: ./lib/windows/queries/windows_anomaly_process-execution.yml
 - path: ./lib/windows/queries/windows_persistence-startup_items.yml
 - path: ./lib/windows/queries/windows_browsere-extensions.yml
 - path: ./lib/windows/queries/windows_new_file_relevant_infection_path.yml
 - path: ./lib/windows/queries/windows_process_no_disk_binary.yml
 - path: ./lib/windows/queries/windows_system_running_processes.yml
 - path: ./lib/windows/queries/windows_new_dir_relevant_infection_path.yml
 - path: ./lib/windows/queries/network_connection_listening.yml
labels:
 - path: ./lib/all/labels/all-parallels-vms.yml
